### ISSUE TITLE
CollegeAI still maintained? 

### ISSUE THREAD

**Issue by jdmcd** [CollegeAI/api#5]
Hi there,

Is CollegeAI still maintained? I noticed that quite a few of the infoIds don't work - `activitiesandorganizations`, for example. I get `Error: Invalid Info Type: activitiesandorganizations`. Additionally some of the pages on the documentation site lead to 404. 

I paid money for the API so I'd like to figure out what the problem is.

**Comment by jdmcd** [comment]
Additionally, can you please let me know how new the data is?

**Comment by seveibar** [comment]
Yes it's still maintained! The documentation is currently getting an overhaul, some info ids may be broken!

**Comment by seveibar** [comment]
The data is updated regularly depending on the underlying sources, we're especially conscious of reported errors in data, so if you see something out of date just shoot an email to support@collegeai.com!
